/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ngramplayground;

import java.util.ArrayList;

/**
 *
 * @author Admin
 */
public class MainForm extends javax.swing.JFrame {

    private TextDataModelWrapper generator = null;
    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgModelType = new javax.swing.ButtonGroup();
        pnlSource = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSource = new javax.swing.JTextArea();
        pnlControl = new javax.swing.JPanel();
        btnBuildMdl = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        pnlModelType = new javax.swing.JPanel();
        rbChar = new javax.swing.JRadioButton();
        rbWord = new javax.swing.JRadioButton();
        rbToken = new javax.swing.JRadioButton();
        lblChainLength = new javax.swing.JLabel();
        sliderChainLength = new javax.swing.JSlider();
        lblUnitSize = new javax.swing.JLabel();
        sbUnitLength = new javax.swing.JSpinner();
        lblTokens = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTokens = new javax.swing.JTextArea();
        pnlDest = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDest = new javax.swing.JTextArea();
        mbMain = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        itemOpenText = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSource.setBorder(javax.swing.BorderFactory.createTitledBorder("Исходный текст"));

        txtSource.setColumns(20);
        txtSource.setFont(txtSource.getFont().deriveFont(txtSource.getFont().getSize()+2f));
        txtSource.setLineWrap(true);
        txtSource.setRows(5);
        txtSource.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtSource);

        javax.swing.GroupLayout pnlSourceLayout = new javax.swing.GroupLayout(pnlSource);
        pnlSource.setLayout(pnlSourceLayout);
        pnlSourceLayout.setHorizontalGroup(
            pnlSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );
        pnlSourceLayout.setVerticalGroup(
            pnlSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pnlControl.setBorder(javax.swing.BorderFactory.createTitledBorder("Управление"));

        btnBuildMdl.setText("Создать модель");
        btnBuildMdl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuildMdlActionPerformed(evt);
            }
        });

        btnGenerate.setText("Генерировать");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        pnlModelType.setBorder(javax.swing.BorderFactory.createTitledBorder("Разбиение"));

        bgModelType.add(rbChar);
        rbChar.setSelected(true);
        rbChar.setText("По символам");

        bgModelType.add(rbWord);
        rbWord.setText("По словам");

        bgModelType.add(rbToken);
        rbToken.setText("По словам (с токенами)");

        javax.swing.GroupLayout pnlModelTypeLayout = new javax.swing.GroupLayout(pnlModelType);
        pnlModelType.setLayout(pnlModelTypeLayout);
        pnlModelTypeLayout.setHorizontalGroup(
            pnlModelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModelTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbChar)
                    .addComponent(rbWord)
                    .addComponent(rbToken))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlModelTypeLayout.setVerticalGroup(
            pnlModelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModelTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbChar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbWord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbToken)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblChainLength.setText("Длина цепи");

        sliderChainLength.setMajorTickSpacing(11);
        sliderChainLength.setMaximum(12);
        sliderChainLength.setMinimum(1);
        sliderChainLength.setMinorTickSpacing(1);
        sliderChainLength.setPaintLabels(true);
        sliderChainLength.setPaintTicks(true);
        sliderChainLength.setSnapToTicks(true);
        sliderChainLength.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sliderChainLength.setName(""); // NOI18N
        sliderChainLength.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderChainLengthStateChanged(evt);
            }
        });

        lblUnitSize.setText("Размер генерации");

        sbUnitLength.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lblTokens.setText("Токены");

        txtTokens.setColumns(20);
        txtTokens.setRows(5);
        txtTokens.setToolTipText("Пишите токен с каждой строки. Чтобы указать перевод строки или табуляцию, впишите \\n или \\t соответственно");
        jScrollPane3.setViewportView(txtTokens);

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlModelType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblChainLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sliderChainLength, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblUnitSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sbUnitLength)
                    .addComponent(lblTokens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(btnBuildMdl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlModelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChainLength)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderChainLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUnitSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sbUnitLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTokens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuildMdl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerate)
                .addContainerGap())
        );

        pnlDest.setBorder(javax.swing.BorderFactory.createTitledBorder("Результат"));

        txtDest.setColumns(20);
        txtDest.setLineWrap(true);
        txtDest.setRows(5);
        txtDest.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtDest);

        javax.swing.GroupLayout pnlDestLayout = new javax.swing.GroupLayout(pnlDest);
        pnlDest.setLayout(pnlDestLayout);
        pnlDestLayout.setHorizontalGroup(
            pnlDestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        pnlDestLayout.setVerticalGroup(
            pnlDestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        menuFile.setText("Файл");

        itemOpenText.setText("Открыть текст...");
        itemOpenText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOpenTextActionPerformed(evt);
            }
        });
        menuFile.add(itemOpenText);

        mbMain.add(menuFile);

        setJMenuBar(mbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        if (null == generator)
            return;
        String destText = generator.generate((int) sbUnitLength.getValue());
        txtDest.setText(destText);
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void sliderChainLengthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderChainLengthStateChanged
        sliderChainLength.setToolTipText(
                "Сейчас: " + Integer.toString(sliderChainLength.getValue())
        );
    }//GEN-LAST:event_sliderChainLengthStateChanged

    private void btnBuildMdlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuildMdlActionPerformed
        String sourceText = txtSource.getText();
        if (rbChar.isSelected()) {
            generator = new TextDataModelWrapperChar();
        } else {
            generator = new TextDataModelWrapperTokenized();
            ArrayList<String> tokens = new ArrayList<>();
            if (rbWord.isSelected()) {
                tokens.add(" ");
            } else {
                for (String token : txtTokens.getText().split("\n")) {
                    tokens.add(token.replaceAll("\\n", "\n").replaceAll("\\r", "\r").replaceAll("\\t", "\t"));
                }
            }
            ((TextDataModelWrapperTokenized)generator).setTokens(tokens);
        }
        int chainLength = sliderChainLength.getValue();
        generator.buildModel(sourceText, chainLength);
        
    }//GEN-LAST:event_btnBuildMdlActionPerformed

    private void itemOpenTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOpenTextActionPerformed
        // TODO реализовать загрузку текста:
    }//GEN-LAST:event_itemOpenTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgModelType;
    private javax.swing.JButton btnBuildMdl;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JMenuItem itemOpenText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblChainLength;
    private javax.swing.JLabel lblTokens;
    private javax.swing.JLabel lblUnitSize;
    private javax.swing.JMenuBar mbMain;
    private javax.swing.JMenu menuFile;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlDest;
    private javax.swing.JPanel pnlModelType;
    private javax.swing.JPanel pnlSource;
    private javax.swing.JRadioButton rbChar;
    private javax.swing.JRadioButton rbToken;
    private javax.swing.JRadioButton rbWord;
    private javax.swing.JSpinner sbUnitLength;
    private javax.swing.JSlider sliderChainLength;
    private javax.swing.JTextArea txtDest;
    private javax.swing.JTextArea txtSource;
    private javax.swing.JTextArea txtTokens;
    // End of variables declaration//GEN-END:variables

}
